enum EventType {
  CREATE = "CREATE",
  CREATE_LINE = "CREATE_LINE",
  CREATE_RECTANGLE = "CREATE_RECTANGLE",
  CREATE_CIRCLE = "CREATE_CIRCLE",
  SELECT = "SELECT",
  PASTE = "PASTE",
  DELETE = "DELETE",
}

export default EventType;
